function suggestEmoji(event) {
    const inputMessage = document.querySelector('.InputMessage').value;
    const outputDiv = document.querySelector('.output');
    const emojiMap = {
        'happy': '😊',
        'sad': '😢',
        'angry': '😠',
        'love': '❤️',
        'laugh': '😂',
        'surprise': '😲',
        'cool': '😎',
        'thumbs up': '👍',
        'thumbs down': '👎',
        'clap': '👏',
        'party': '🎉',
        'heart': '💗',
        'smile': '😃',
        'cry': '😭',
        'kiss': '😘',
        'wink': '😉',
        'sleep': '😴',
        'money': '💰',
        'fire': '🔥',
        'star': '⭐',
        'sun': '☀️',
        'moon': '🌙',
        'rain': '🌧️',
        'snow': '❄️',
        'thunder': '⚡',
        'rainbow': '🌈',
        'flower': '🌺',
        'tree': '🌳',
        'car': '🚗',
        'plane': '✈️',
        'ship': '🚢',
        'bike': '🚲',
        'food': '🍔',
        'drink': '🍺',
        'music': '🎶',
        'dance': '💃',
        'sports': '⚽',
        'game': '🎮',
        'book': '📚',
        'camera': '📷',
        'phone': '📱',
        'computer': '💻',
        'robot': '🤖',
        'alien': '👽',
        'ghost': '👻',
        'poop': '💩',
        'unicorn': '🦄',
        'cat': '🐱',
        'dog': '🐶',
        'bird': '🐦',
        'fish': '🐟',
        'butterfly': '🦋',
        'bug': '🐛',
        'face with tears of joy': '😂',
        'red heart': '❤️',
        'smiling face with heart-eyes': '😍',
        'rolling on the floor laughing': '🤣',
        'face with open mouth and cold sweat': '😓',
        'face with steam from nose': '😤',
        'face with symbols over mouth': '🤫',
        'face with medical mask': '😷',
        'face with thermometer': '🤒',
        'face with head-bandage': '🤕',
        'nauseated face': '🤢',
        'face vomiting': '🤮',
        'sneezing face': '🤧',
        'smiling face with sunglasses': '😎',
        'star-struck': '🤩',
        'face with monocle': '🧐',
        'nerd face': '🤓',
        'thinking face': '🤔',
        'face with raised eyebrow': '🤨',
        'face with hand over mouth': '🤭',
        'shushing face': '🤫',
        'face with symbols over mouth': '🤬',
        'face with spiral eyes': '🤯',
        'exploding head': '🤯',
        'zany face': '🤪',
        'face with raised eyebrow': '🤨',
        'face with hand over mouth': '🤭',
        'face with open eyes and hand over mouth': '🙀',
        'weary cat face': '😿',
        'crying cat face': '😿',
        'pouting cat face': '😾',
        'slightly frowning face': '🙁',
        'frowning face': '☹️',
        'face with open mouth': '😮',
        'hushed face': '😯',
        'sleepy face': '😪',
        'tired face': '😫',
        'yawning face': '🥱',
        'face with steam from nose': '😤',
        'enraged face': '😡',
        'angry face': '😠',
        'face with symbols over mouth': '🤬',
        'face with head-bandage': '🤕',
        'money-mouth face': '🤑',
        'smiling face with dollar eyes': '🤑',
        'money-mouth face': '🤑',
        'face with dollar sign eyes': '🤑',
        'astonished face': '😲',
        'flushed face': '😳',
        'face savoring food': '😋',
        'face with tongue': '😛',
        'winking face': '😉',
        'kissing face': '😗',
        'kissing face with closed eyes': '😚',
        'kissing face with smiling eyes': '😙',
        'face blowing a kiss': '😘',
        'face with hearts': '🥰',
        'smiling face with hearts': '🥰',
        'star-struck': '🤩',
        'grinning face': '😀',
        'grinning face with big eyes': '😃',
        'grinning face with smiling eyes': '😄',
        'beaming face with smiling eyes': '😁',
        'grinning squinting face': '😆',
        'grinning face with sweat': '😅',
        'winking face': '😉',
        'smiling face with smiling eyes': '😊',
        'slightly smiling face': '🙂',
        'upside-down face': '🙃',
        'melting face': '🫠',
        'face with open eyes and hand over mouth': '🙀',
        'weary cat face': '😿',
        'crying cat face': '😿',
        'pouting cat face': '😾',
        'see-no-evil monkey': '🙈',
        'hear-no-evil monkey': '🙉',
        'speak-no-evil monkey': '🙊',
        'skull': '💀',
        'skull and crossbones': '☠️',
        'pile of poo': '💩',
        'peach': '🍑',
        'eggplant': '🍆',
        'middle finger': '🖕',
        'victory hand': '✌️',
        'crossed fingers': '🤞',
        'call me hand': '🤙',
        'sign of the horns': '🤘',
        'raised fist': '✊',
        'raised hand': '✋',
        'wave': '👋',
        'clapping hands': '👏',
        'writing hand': '✍️',
        'selfie': '🤳',
        'nail polish': '💅',
        'lipstick': '💄',
        'ring': '💍',
        'gem stone': '💎',
        'muted speaker': '🔇',
        'speaker low volume': '🔈',
        'speaker medium volume': '🔉',
        'speaker high volume': '🔊',
        'battery': '🔋',
        'electric plug': '🔌',
        'magnifying glass tilted left': '🔍',
        'magnifying glass tilted right': '🔎',
        'locked': '🔒',
        'unlocked': '🔓',
        'locked with pen': '🔏',
        'locked with key': '🔐',
        'key': '🔑',
        'old key': '🗝️',
        'hammer': '🔨',
        'axe': '🪓',
        'pick': '⛏️',
        'hammer and pick': '⚒️',
        'tools': '🧰',
        'nut and bolt': '🔩',
        'gear': '⚙️',
        'chains': '⛓️',
        'magnet': '🧲',
        'syringe': '💉',
        'pill': '💊',
        'smoking': '🚬',
        'coffin': '⚰️',
        'funeral urn': '⚱️',
        'moai': '🗿',
        'oil drum': '🛢️',
        'crystal ball': '🔮',
        'nazar amulet': '🧿',
        'barber pole': '💈',
        'alembic': '🧪',
        'test tube': '🧫',
        'petri dish': '🧫',
        'dna': '🧬',
        'microscope': '🔬',
        'telescope': '🔭',
        'satellite antenna': '📡',
        'spool of thread': '🧵',
        'yarn': '🧶',
        'safety pin': '🧷',
        'paperclip': '📎',
        'scissors': '✂️',
        'pushpin': '📌',
        'straight pin': '🧷',
        'file folder': '📁',
        'open file folder': '📂',
        'card index dividers': '🗂️',
        'calendar': '📅',
        'tear-off calendar': '🗓️',
        'spiral notepad': '🗒️',
        'spiral calendar': '🗓️',
        'card index': '🗂️',
        'chart increasing': '📈',
        'chart decreasing': '📉',
        'bar chart': '📊',
        'clipboard': '📋',
        'paperclip': '📎',
        'straight pin': '🧷',
        'pushpin': '📌',
        'scissors': '✂️',
        'desktop computer': '🖥️',
        'printer': '🖨️',
        'computer mouse': '🖱️',
        'trackball': '🖲️',
        'computer keyboard': '⌨️',
        'computer disk': '💽',
        'floppy disk': '💾',
        'optical disk': '📀',
        'dvd': '📀',
        'abacus': '🧮',
        'movie camera': '🎥',
        'film projector': '📽️',
        'film strip': '🎞️',
        'clapper board': '🎬',
        'television': '📺',
        'camera': '📷',
        'camera with flash': '📸',
        'video camera': '📹',
        'videocassette': '📼',
        'magnifying glass tilted left': '🔍',
        'magnifying glass tilted right': '🔎',
        'candle': '🕯️',
        'light bulb': '💡',
        'flashlight': '🔦',
        'red paper lantern': '🏮',
        'diya lamp': '🪔',
        'notebook with decorative cover': '🔖',
        'closed book': '📕',
        'open book': '📖',
        'green book': '📗',
        'blue book': '📘',
        'orange book': '📙',
        'books': '📚',
        'notebook': '📓',
        'ledger': '📒',
        'page with curl': '📃',
        'scroll': '📜',
        'newspaper': '📰',
        'rolled-up newspaper': '🗞️',
        'bookmark tabs': '📑',
        'bookmark': '🔖',
        'label': '🏷️',
        'money bag': '💰',
        'coin': '💵',
        'yen banknote': '💴',
        'dollar banknote': '💵',
        'euro banknote': '💶',
        'pound banknote': '💷',
        'money with wings': '💸',
        'credit card': '💳',
        'receipt': '🧾',
        'chart increasing with yen': '💹',
        'envelope': '✉️',
        'e-mail': '📧',
        'incoming envelope': '📨',
        'envelope with arrow': '📩',
        'love letter': '💌',
        'postbox': '📮',
        'mailbox closed': '📪',
        'mailbox with raised flag': '📫',
        'mailbox with mail': '📬',
        'mailbox with no mail': '📭',
        'package': '📦',
        'postal horn': '📯',
        'door': '🚪',
        'bed': '🛏️',
        'couch and lamp': '🛋️',
        'chair': '🪑',
        'toilet': '🚽',
        'shower': '🚿',
        'bathtub': '🛀',
        'mouse trap': '🪤',
        'razor': '🪒',
        'toothbrush': '🪥',
        'potted plant': '🪴',
        'wood': '🪵',
        'hammer and nail': '🔨⚒️',
        'screwdriver': '🔩',
        'wrench': '🔧',
        'hammer and wrench': '🛠️',
        'dagger': '🗡️',
        'crossed swords': '⚔️',
        'shield': '🛡️',
        'bow and arrow': '🏹',
        'boomerang': '🪃',
        'bullet': '🔫',
        'bomb': '💣',
        'firecracker': '🧨',
        'crystal ball': '🔮',
        'magic wand': '🪄',
        'alembic': '🧪',
        'test tube': '🧫',
        'petri dish': '🧫',
        'dna': '🧬',
        'microscope': '🔬',
        'telescope': '🔭',
        'satellite': '🛰️',
        'syringe': '💉',
        'pill': '💊',
        'adhesive bandage': '🩹',
        'stethoscope': '🩺',
        'x-ray': '🩻',
        'crutch': '🩼',
        'wheelchair': '🦽',
        'probing cane': '🦯',
        'leg': '🦵',
        'foot': '🦶',
        'ear': '👂',
        'nose': '👃',
        'brain': '🧠',
        'tooth': '🦷',
        'bone': '🦴',
        'eyes': '👀',
        'tongue': '👅',
        'lips': '👄',
        'baby': '👶',
        'child': '🧒',
        'boy': '👦',
        'girl': '👧',
        'person': '🧑',
        'adult': '🧑',
        'man': '👨',
        'woman': '👩',
        'person with blond hair': '👱',
        'older adult': '🧓',
        'old man': '👴',
        'old woman': '👵',
        'person frowning': '🙍',
        'person pouting': '🙎',
        'person gesturing no': '🙅',
        'person gesturing ok': '🙆',
        'person tipping hand': '💁',
        'person raising hand': '🙋',
        'flower': '🌺',
        'tree': '🌳',
        'car': '🚗',
        'plane': '✈️',
        'ship': '🚢',
        'bike': '🚲',
        'food': '🍔',
        'drink': '🍺',
        'music': '🎶',
        'dance': '💃',
        'sports': '⚽',
        'game': '🎮',
        'book': '📚',
        'camera': '📷',
        'phone': '📱',
        'computer': '💻',
        'robot': '🤖',
        'alien': '👽',
        'ghost': '👻',
        'poop': '💩',
        'unicorn': '🦄',
        'cat': '🐱',
        'dog': '🐶',
        'bird': '🐦',
        'fish': '🐟',
        'butterfly': '🦋',
        'bug': '🐛'
    };

    let emojiText = '';
    const words = inputMessage.toLowerCase().split(' ');

    for (let i = 0; i < words.length; i++) {
        const word = words[i];
        if (emojiMap[word]) {
            emojiText += emojiMap[word] + ' ';
        } else {
            emojiText += word + ' ';
        }
    }

    outputDiv.textContent = emojiText.trim();
}
  function clearOutput() {
    document.querySelector('.output').textContent = '';
    document.querySelector('.InputMessage').value = '';
  }